# SPDX-FileCopyrightText: 2020 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version: 2
updates:
  - package-ecosystem: composer
    directories:
      - "/"
      - "/vendor-bin/csfixer"
      - "/vendor-bin/phpunit"
      - "/vendor-bin/psalm"
    commit-message:
      prefix: "ci"
      include: "scope"
    versioning-strategy: "increase"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Berlin
    labels:
      - 3. to review
      - dependencies

  # NPM: Code-Dependencies
  - package-ecosystem: npm
    directory: "/"
    commit-message:
      prefix: "build"
      include: "scope"
    versioning-strategy: "increase"
    schedule:
      interval: weekly
      day: saturday
      time: "03:00"
      timezone: Europe/Berlin
    labels:
      - 3. to review
      - dependencies
