# SPDX-FileCopyrightText: 2015-2026 ownCloud, Inc.
# SPDX-License-Identifier: AGPL-3.0-or-later
filter:
    excluded_paths:
        - 'js/jquery*'
        - 'l10n/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage:
        timeout: 7200 # Timeout in seconds: 2 hours
